### PR TITLE
Include lib-cov folder via NPM

### PR DESCRIPTION
**Pull request by andrewbranch**
Continuation of #4

### CODE REVIEW

**Comment by andrewbranch** [comment]
Sorry I didn’t notice this before you released 2.2.1 :grimacing:

**Comment by azproduction** [comment]
No problem, I did not check it also. Thanks for PR! `promise-queue@2.2.2`

**Comment by andrewbranch** [comment]
Hmm, I'm still not getting the folder when referencing the git URL from package.json... let me try 2.2.2 straight from npm.

**Comment by andrewbranch** [comment]
Yep, confirmed working with Webpack and `promise-queue@2.2.2`. Thanks!

**Pull request merged**
