### PR TITLE
add lib-cov folder to allow browserify builds

### PR DESCRIPTION
**Pull request by tonypee**
browserify cannot use the library as it tries to pre-process all 'requires' at build time. So, it fails as it cannot include the './lib-cov' folder

### CODE REVIEW

**Comment by voltrevo** [comment]
@tonypee I was able to achieve the same result by changing `require('./lib-cov');` to `require('./lib-cov' + '');`. Debatable whether that's preferable but I'd lean towards that being simpler.

**Comment by darlanalves** [comment]
@azproduction Hi! 
I just stumble upon this issue too. Mind looking at this one?

**Comment by prewk** [comment]
+1

**Comment by andrewbranch** [comment]
Yeah, um, status on this? Same issue with Webpack.

**Comment by azproduction** [comment]
I am sorry guys for that huge delay!
`promise-queue@2.2.1`

**Pull request merged**
