### PR TITLE
Jump the queue !

### PR DESCRIPTION
**Pull request by hugoclrd**
Added the `.addNow()` method, as described in #11. Style WIP, it needs to be unit tested.

### CODE REVIEW

**Comment by mateuszmazurek** [comment]
+1

**Comment by azproduction** [comment]
Thank you for this PR! There are a few thing can be improved, imo:
```
// no reason to create a partially applied function here
Queue.prototype.addNow = function (promiseGenerator) {
     return this._genericAdd(promiseGenerator, 'unshift');
};
```

**Comment by hugocaillard** [comment]
Fixed @azproduction 😉

**Comment by mayeaux** [comment]
It was never merged?

**Pull request closed without merging**
